version: '1.0.0'

services:

#UI http://localhost:15800/#/
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    container_name: RabbitMQ
    hostname: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=StasPI
      - RABBITMQ_DEFAULT_PASS=Password1
    ports:
      # AMQP protocol port
      - 5800:5672
      - 15800:15672
    volumes:
      - ./etc/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./etc/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

#connection to server at "PostgreSQL" (172.21.0.3), port 5432
  db:
    restart: unless-stopped
    image: postgres
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: StasPI
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Password1
    volumes:
      - local_pgdata:/var/lib/postgresql/data

#UI http://localhost:5050/browser/
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: StasPI@github.com
      PGADMIN_DEFAULT_PASSWORD: Password1
    volumes:
      - ./etc/pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./etc/pgadmin/pgpass:/pgadmin4/pgpass # passwords for the connections in this file

volumes:
  local_pgdata:
  pgadmin-data: